### ISSUE TITLE
VOWEL SIGN O overlaps next consonant

### ISSUE THREAD

**Issue by rdwnnr** [notofonts/buginese#1]
**Is your feature request related to a problem? Please describe.**
U+1A1A Buginese Vowel Sign O struck to the next consonant that draw line from below. 

**Describe the solution you'd like**
As you can see now ᨑᨚᨓ (U+1A1A ᨚ is stick to U+1A13 ᨓ) and it is expecting to form like this:
ᨑᨚ ᨓ (like to have a little space there).

**Describe alternatives you've considered**
I consider making a slope tolerance for U+1A19, U+1A1A, U+1A1B, U+1A1E. In traditional writing it also common, even sometimes it form vertically. It is good to make it a bit contrast from the consonant.

**Additional context**
Maybe the font that I have costumized here: https://rdwnnr.github.io/latin2lontara/, can be used as a reference.

**Comment by simoncozens** [comment]
I've added a little space after the o-vowel when it follows glyphs with a bottom-left tail:

![shape](https://user-images.githubusercontent.com/106728/186179550-47d17464-3e07-481d-b61a-7c6a7ac5d17c.png)

Maybe it would be better to re-draw the vowel signs to make them more vertical, but I don't feel comfortable doing that; it's more a job for a designer. Hopefully this will make things better.

**Comment by rdwnnr** [comment]
![ᨒᨚᨈᨑ](https://github.com/user-attachments/assets/c0263fb9-fb07-43ff-bacf-556e5c51894c)
I have adjusted the width of U+1A1A glyph on the glyphs file, is that small change will solve the problem?
